### ISSUE TITLE
Error 500 | Internal Server Error

### ISSUE THREAD

**Issue by yasinyilmaz1** [yolanmees/Spikster#11]
I reinstalled the panel on a clean Ubuntu 22.04. After installing it and making changes in the fields of changing password and changing e-mail, I encountered the problem as shown on the screen. Also, the same problem occurs when I try to give a domain to the panel, and the icon on the server RAM, CPU, HDD sections and the icon on the server restart buttons appear to be constantly rotating.

![Screenshot from 2023-10-20 16-55-03](https://github.com/yolanmees/Spikster/assets/80541213/15a89864-114c-4a50-aef0-34987bbeaeb7)
![Screenshot from 2023-10-20 16-56-05](https://github.com/yolanmees/Spikster/assets/80541213/8c23463f-6346-4cd2-9be6-f15fc8e302c6)
![Screenshot from 2023-10-20 16-56-13](https://github.com/yolanmees/Spikster/assets/80541213/6adc8270-d2dd-4fc3-8392-5948649b397f)
![Screenshot from 2023-10-20 16-56-55](https://github.com/yolanmees/Spikster/assets/80541213/e8e68843-e601-495f-a304-1459d66452d2)

**Comment by yolanmees** [comment]
Hi @yasinyilmaz1 

Thanks for tying out Spikster! I just made some major adjustments from how Cipi used to do it. Previously, an SSH connection was made to the server for like everything (stats, restarts, etc). I changed this to API calls. There are a number of components in the panel that do not yet use the API. But I'm currently rewriting all these components. So there will be an update for that very soon. (Spikster is currently still in an alpha phase, because I first wanted to make some structural adjustments to how Cipi worked)

I will also look at what is going wrong when updating passwords, etc. and immediately include them in this update. And I will update you here.

**Comment by yolanmees** [comment]
Hi @yasinyilmaz1 ,

The password update must have simply been an error with the Jetstream and Livewire versions. This has been updated. 

The server components have also been updated with the new method. So this should work again now. I have currently kept the dashboard somewhat empty because it will receive a major overhaul in the future.

There is currently no manual to update Spikster. But for this update you can simply download an update from GitHub in the root folder of the Spikster application.
