### ISSUE TITLE
Issues installing on Ubuntu 22.04

### ISSUE THREAD

**Issue by fastmover** [yolanmees/Spikster#4]
Using Vultr hosting, the Mysql prompts differ and break installation script.  I think there's other issues too but I'm still running them down. The PHP JSON module also errors installing. Been editing the installation script and testing, I'll post more as I figure it out. I'll post a pull request if we can figure out if it's not just Vultr's Ubuntu images. I've been using Cipi for a couple years on Vultr with Ubuntu 20.04 with no issues.

**Comment by yolanmees** [comment]
If you can share your output here I can see how we can solve this. Because I have no clue what's going wrong right now.

Are you logged in as root? Otherwise you definitely should use sudo -s before installing. 

(Thanks for trying out Spikster, I have only just started development. But the adjustments that I have made to my own environment in the last six months have already been integrated. If there are still features on your wishlist, you can certainly pass them on)

**Comment by fastmover** [comment]
Yeah, the default user on Vultr's Ubuntu images is root

**Comment by yolanmees** [comment]
I just set up a server via voltr and there is no interaction possible via the web console. If you connect via your OS terminal with SSH then this should work.

**Comment by fastmover** [comment]
Yeah I know I've been using Vultr for years now. Just a nice cheap cloud VM. Well one of the issues was my sequel installation, the expect was looking for a password input when there wasn't any. I finally got the installation all the way but there's still some issues and the only way I was able to do that was by chunking out the installation script and running section at a time and fixing issues as I go. I'm going to keep working on rewriting the installation script until I can get it to install in one try.
